- name: Authenticate to OpenShift Cluster {{ openshift_test_url }}
  command: "oc login {{ openshift_test_url }} --token={{ openshift_test_token }} --insecure-skip-tls-verify"

- name: Create Production Project
  command: "oc new-project {{ openshift_app_name }}-test"
