- name: Authenticate to OpenShift Cluster {{ openshift_prod_url }}
  command: "oc login {{ openshift_prod_url }} --token={{ openshift_prod_token }} --insecure-skip-tls-verify --insecure-skip-tls-verify"

- name: Get SCC labels from production
  command: "oc get project dbtest2 -o yaml  |sed '/creationTimestamp/d' |sed '/resourceVersion/d' |sed '/selfLink/d' |sed '/uid:/d' >/tmp/dr-project.yaml"

- name: Get Secrets from production
  command: "oc get secret mariadb -o yaml --export=true |sed '/creationTimestamp/d' |sed '/selfLink/d' >/tmp/secret.yaml"

- name: Authenticate to OpenShift Cluster {{ openshift_test_url }}
  command: "oc login {{ openshift_test_url }} --token={{ openshift_test_token }} --insecure-skip-tls-verify"

- name: Create DR Project
  command: "oc create -f /tmp/dr-project.yaml"

- name: Create Secrets in DR project
  command: "oc create -f /tmp/secret.yaml -n {{ openshift_app_name }}"
