- name: Authenticate to OpenShift Cluster {{ openshift_test_url }}
  command: "oc login {{ openshift_test_url }} --token={{ openshift_test_token }} --insecure-skip-tls-verify"

- name: Remove Test Project
  command: "oc delete project {{ openshift_app_name }}-test" 
