- name: Authenticate to OpenShift Cluster {{ openshift_prod_url }}
  command: "oc login {{ openshift_prod_url }} --token={{ openshift_prod_token }} --insecure-skip-tls-verify --insecure-skip-tls-verify"

- name: Create Production Project {{ openshift_app_name }}-prod
  command: "oc new-project {{ openshift_app_name }}-prod"
