---
- name: Inventory OpenShift Nodes
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars:
    openshift_prod_project_name: prod123
    openshift_test_project_name: test123
    

  tasks:
  - import_role:
      name: remove-production-project
  - import_role:
      name: remove-test-project
