---
- name: Inventory OpenShift Nodes
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:
  - import_role:
      name: remove-production-project
  - import_role:
      name: remove-test-project
